{
	"version": 1592014673,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bg-sheet0.png",
		"images/bubble1841301_-sheet0.png",
		"images/particles.png",
		"images/backgrounddesert-sheet0.png",
		"images/red_button-sheet0.png",
		"images/green_button-sheet0.png",
		"images/bubble-sheet0.png",
		"images/cloud-sheet0.png",
		"images/sun-sheet0.png",
		"images/treelongsnow-sheet0.png",
		"images/treefrozen-sheet0.png",
		"images/shadedlight-sheet0.png",
		"images/cloud2-sheet0.png",
		"images/backgroundempty-sheet0.png",
		"images/cloud3-sheet0.png",
		"images/icons8topmenu-sheet0.png",
		"images/backgroundforest-sheet0.png",
		"images/bubble3-sheet0.png",
		"images/bubble1841301_2-sheet0.png",
		"images/background-sheet0.png",
		"images/blue_button-sheet0.png",
		"images/bgloading-sheet0.png",
		"images/sprite-sheet0.png",
		"images/tiledbackground.png",
		"images/backgroundcastles-sheet0.png",
		"images/icons8home-sheet0.png",
		"media/mouse-click-00-c-fesliyanstudios.com.m4a",
		"media/mouse-click-00-c-fesliyanstudios.com.ogg",
		"media/suara-gelembung-pecah.m4a",
		"media/suara-gelembung-pecah.ogg",
		"media/harvest moon save the homeland - spring farm (online-audio-converter.com).m4a",
		"media/harvest moon save the homeland - spring farm (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}